#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments
#------------------------------------------------------------------------------

#wmakeLnInclude interfacialModels

wmake $targetType twoPhaseSystemPbeBubble
#wmake $targetType interfacialModels
#wmake $targetType phaseCompressibleTurbulenceModels
#wmake $targetType pbeBubbleFoam

#------------------------------------------------------------------------------
